### ISSUE TITLE
Compatibility with CiviCRM 5

### ISSUE THREAD

**Issue by mikemazurkiewicz** [Skvare/com.skvare.lineitemreport#10]
Hi,
I have tried to use this extension with CiviCRM 5.11.0 and keep getting PHP errors relating to the code. I have tried to fix some, but now I have warning with the core of CiviCRM.
Is there an update coming for newer versions of CiviCRM?
Thanks,
Mike.

**Comment by Peter-Petrik** [comment]
Thanks for testing this out Mike. Can you please provide documentation of which notices/warnings/errors you're seeing, steps to replicate, details of your setup (version of PHP, MySQL, CiviCRM being tested, Drupal version, etc)?

**Comment by mikemazurkiewicz** [comment]
Hi Peter,
I have CiviCRM 5.12.0 installed on Joomla 3.9.5. The installation was error-less.
When I click on the template, Participant Line Items, to create a new report, I get a page with the following errors on an otherwise blank page:
 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/rbsports/public_html/administrator/components/com_civicrm/civicrm/ext/com.skvare.lineitemreport-master/CRM/Lineitemreport/Report/Form/LineItem.php on line 385
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/rbsports/public_html/administrator/components/com_civicrm/civicrm/ext/com.skvare.lineitemreport-master/CRM/Lineitemreport/Report/Form/LineItem.php on line 396
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/rbsports/public_html/administrator/components/com_civicrm/civicrm/ext/com.skvare.lineitemreport-master/CRM/Lineitemreport/Report/Form/LineItem.php on line 407
> 
> Fatal error: Access level to CRM_Lineitemreport_Report_Form_LineItem::setEntityRefDefaults() must be public (as in class CRM_Report_Form) in /home/rbsports/public_html/administrator/components/com_civicrm/civicrm/ext/com.skvare.lineitemreport-master/CRM/Lineitemreport/Report/Form/LineItem.php on line 7

I originally went and updated the above mentions lines of code, but I started to get other error message relating to what I believe were core files.
Thanks,
Mike

**Comment by Peter-Petrik** [comment]
Please provide your version of PHP, MySQL, and specific URL paths where you are encountering
these warnings.

**Comment by mikemazurkiewicz** [comment]
Hi,
The info:
Database Server version: 5.6.40-84.0-log - Percona Server (GPL), Release 84.0, Revision 47234b3 
PHP version: 7.3.4
https://www.rbsportsboosters.com/administrator/?option=com_civicrm&task=civicrm/report/lineitem/participant&reset=1

**Comment by Peter-Petrik** [comment]
I'd recommend upgrading to the latest CiviCRM 5.12.3
Also note that per [System requirements](https://docs.civicrm.org/sysadmin/en/latest/requirements/) testing on PHP 7.3 is incomplete. You may consider downgrading to PHP 7.2.

**Comment by mikemazurkiewicz** [comment]
Hi,
I downgraded to 7.2.17. and upgraded to CiviCRM 5.12.3.  Receiving the error message:

> Fatal error: Access level to CRM_Lineitemreport_Report_Form_LineItem::setEntityRefDefaults() must be public (as in class CRM_Report_Form) in /home/rbsports/public_html/administrator/components/com_civicrm/civicrm/ext/com.skvare.lineitemreport-master/CRM/Lineitemreport/Report/Form/LineItem.php on line 7

**Comment by sunilpawar** [comment]
@mikemazurkiewicz  we have fixed warning and fatal Error issue, can you please try now?
